# testing environment
master-cdn-deploy:
    stage: deploy
    before_script: 
    - rsync -av --delete ./public/data/ /output/plunder-transfer-map/data/
    script:
    - npm install
    - npm run build
    - rsync -av --delete ./build/ /output/plunder-transfer-map/
    only:
    - live-data
    tags:
    - live-data
  